### ISSUE TITLE
Installation instructions hard to understand

### ISSUE THREAD

**Issue by forfeen** [Sahanon-P/Noxus-Project#63]
In my opinion, I think
1. Formatting for each step hard to read.  Let's see [18F Guides Template](https://github.com/18F/guides-template/blob/master/README.md) for nicely and clearly formatting. 
2. Please don't assume that everyone has environment matched your requirement. Tell them to install , see [this](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/).
3. Many user, many devices. Don't forget that the user didn't use the same the device or _OS_ . Please add how to install on On MacOS, Linux and Windows.

**Comment by Sahanon-P** [comment]
Thanks for correcting our mistake. I've change the guide as you recommended if something don't match your expectations feel free to reopen this issues.

We appreciate your help for improve our project. Thank again.
