### ISSUE TITLE
Error message hard to see

### ISSUE THREAD

**Issue by forfeen** [Sahanon-P/Noxus-Project#64]
Error message, when the user input the wrong password, hard to see it. 
<img width="560" alt="Screen Shot 2563-11-29 at 17 17 35" src="https://user-images.githubusercontent.com/52417088/100539971-c81afa00-326c-11eb-8fb5-93debbba35f4.png">

**Comment by Sahanon-P** [comment]
Thanks for mentioned that we will change the color and the format as soon as possible
