### ISSUE TITLE
The color style of alert message

### ISSUE THREAD

**Issue by JirawadeeSampusri** [Sahanon-P/Noxus-Project#67]
<img width="563" alt="Screen Shot 2563-11-29 at 21 03 59" src="https://user-images.githubusercontent.com/48781579/100544176-85feb200-3286-11eb-8d94-bebccdd83863.png">
 It is hard to see the alert message. You should change color style of it.

**Comment by VonKiar** [comment]
This is fixed on development branch and I will merge them once the other features are also done , Thanks :D
