### ISSUE TITLE
In README, show the URL instead of "click".

### ISSUE THREAD

**Issue by jbrucker** [Sahanon-P/Noxus-Project#68]
In Github markdown, you can create a hyperlink that also displays
the URL by surrounding it with <...>, as in:

<https://yahoo.com>

This let's anyone use copy & paste if they want,  Better than "click" or "here".

**Comment by Sahanon-P** [comment]
Thanks for your suggestion I'm really agreed that it more useful to provide the whole url than just "click" and I have fixed it in the README so you can check it out. Please feel free to reopen if anything didn't match your expectation.
