### ISSUE TITLE
Search box does not work if the word contain non alphabetical character.

### ISSUE THREAD

**Issue by phuwanutj** [Sahanon-P/Noxus-Project#69]
URL: https://noxus-project.herokuapp.com/

Search box does not work if the word contain non alphabetical character. Non alphabetical character contain number and symbol.
I think the search filter should show the "champion not found" or a warning message telling you that you can't use non alphabetical character. 

How to reproduce:
1. Type the - into the search box .
2. Click the search button.
3. The web should show the "Champion Not Found!" message since there are no champion that contain "-" in its name.

**Comment by Raikirieiei** [comment]
I'll try to adjust it, Thank for mention this issue!

**Comment by Raikirieiei** [comment]
Just finish fixing this issue, You can check it out!
