### ISSUE TITLE
Appearance: On the build create page, the UI is not user friendly.

### ISSUE THREAD

**Issue by ZEZAY** [Sahanon-P/Noxus-Project#70]
The text color and the laout are hard to see.

URL: https://noxus-project.herokuapp.com/build/create/

![image](https://user-images.githubusercontent.com/44806732/100922991-21a35300-3511-11eb-8b1c-71066cf1bb00.png)

**Comment by VonKiar** [comment]
After I'm done extracting their elements then I can easily customize it. :D Now it is at default setting.

**Comment by Sahanon-P** [comment]
Im sorry but this is not done yet so i reopen it.

**Comment by Sahanon-P** [comment]
I will close it when it has been merge.  @VonKiar

**Comment by Raikirieiei** [comment]
We fixed this problem, Thank you for mentioning.
