### ISSUE TITLE
Functionality: Duplicate spells, runes are available for the user to create

### ISSUE THREAD

**Issue by LevNut** [Sahanon-P/Noxus-Project#71]
<img width="896" alt="Screen Shot 2563-12-03 at 16 15 26" src="https://user-images.githubusercontent.com/59854352/100989052-fa856980-3582-11eb-90df-8ad8b677c190.png">

I think that you shouldn't allows the user to create the same summoner's spell and sub-runes in "create_build" function
Also, the main rune and sub-rune are not related. According to the picture, Glacial Augment is in Inspiration's rune while sub-comment "Ghost-Poro" is in Domination's rune.

**Comment by VonKiar** [comment]
Thanks for finding this bug, our most capable back-end developer hands will handle this outrageous error.

**Comment by Firstyfirst** [comment]
Our application have the feature to help the user to remember and create their own build, so the user who play this game should know by themselves which rune or item can use at the same time. You can freely create your own build on our web application, but you can not use this build in the real game. We can conclude that it is the user error. Finally, this comment is the good suggestion for our project. If we have the opportunity to do it again, we will get this suggestion to improve our project.

**Comment by VonKiar** [comment]
As developer suggested, it is a freely customizable feature that we'd like the user to create whatever they like but if wether the build user create is functional or not then it is depends on user's common senses and ideas.
