### ISSUE TITLE
DEBUG is not closed

### ISSUE THREAD

**Issue by pattarinn** [Sahanon-P/Noxus-Project#72]
When I tried to click login again and again many times, I got this
<img width="1421" alt="Screen Shot 2563-12-04 at 20 54 21" src="https://user-images.githubusercontent.com/59819965/101172168-66df9600-3673-11eb-961d-f3f022e59afd.png">

You should close it due to the security problems.

**Comment by Sahanon-P** [comment]
I've already change debug setting to False and also hide the secret key. Thanks for mentioned that!
